version: "3.4"

services:
  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:latest
    container_name: saleor-dashboard
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    restart: unless-stopped

networks:
  saleor-bridge-network:
    driver: bridge
